// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealEstatePortal.Infrastructure;

#nullable disable

namespace RealEstatePortal.Infrastructure.Migrations
{
    [DbContext(typeof(RealEstateDbContext))]
    [Migration("20250822014035_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RealEstatePortal.Domain.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("CarSpots")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "103 Peshawar Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 2,
                            City = "Peshawar",
                            Description = "Spacious luxury apartment located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 49434963m,
                            Title = "Luxury Apartment in Peshawar"
                        },
                        new
                        {
                            Id = 2,
                            Address = "52 Lahore Road",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Lahore",
                            Description = "Spacious family home located in Lahore. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 101202m,
                            Title = "Family Home in Lahore"
                        },
                        new
                        {
                            Id = 3,
                            Address = "141 Multan Road",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Multan",
                            Description = "Spacious office space located in Multan. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 54061732m,
                            Title = "Office Space in Multan"
                        },
                        new
                        {
                            Id = 4,
                            Address = "103 Sialkot Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 2,
                            City = "Sialkot",
                            Description = "Spacious modern villa located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 253236m,
                            Title = "Modern Villa in Sialkot"
                        },
                        new
                        {
                            Id = 5,
                            Address = "161 Lahore Road",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 1,
                            City = "Lahore",
                            Description = "Spacious studio flat located in Lahore. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 54568624m,
                            Title = "Studio Flat in Lahore"
                        },
                        new
                        {
                            Id = 6,
                            Address = "23 Quetta Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Quetta",
                            Description = "Spacious luxury apartment located in Quetta. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 7238858m,
                            Title = "Luxury Apartment in Quetta"
                        },
                        new
                        {
                            Id = 7,
                            Address = "103 Islamabad Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Islamabad",
                            Description = "Spacious family home located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 232128m,
                            Title = "Family Home in Islamabad"
                        },
                        new
                        {
                            Id = 8,
                            Address = "54 Karachi Road",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Karachi",
                            Description = "Spacious townhouse located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 58419409m,
                            Title = "Townhouse in Karachi"
                        },
                        new
                        {
                            Id = 9,
                            Address = "103 Karachi Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Karachi",
                            Description = "Spacious modern villa located in Karachi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 170471m,
                            Title = "Modern Villa in Karachi"
                        },
                        new
                        {
                            Id = 10,
                            Address = "7 Faisalabad Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious office space located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 6096229m,
                            Title = "Office Space in Faisalabad"
                        },
                        new
                        {
                            Id = 11,
                            Address = "29 Gujranwala Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Gujranwala",
                            Description = "Spacious commercial plot located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 140736m,
                            Title = "Commercial Plot in Gujranwala"
                        },
                        new
                        {
                            Id = 12,
                            Address = "147 Faisalabad Road",
                            Bathrooms = 4,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious farmhouse located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 149234m,
                            Title = "Farmhouse in Faisalabad"
                        },
                        new
                        {
                            Id = 13,
                            Address = "90 Karachi Road",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 0,
                            City = "Karachi",
                            Description = "Spacious shop located in Karachi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 126499m,
                            Title = "Shop in Karachi"
                        },
                        new
                        {
                            Id = 14,
                            Address = "197 Rawalpindi Road",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Rawalpindi",
                            Description = "Spacious luxury apartment located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 60122m,
                            Title = "Luxury Apartment in Rawalpindi"
                        },
                        new
                        {
                            Id = 15,
                            Address = "5 Quetta Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Quetta",
                            Description = "Spacious townhouse located in Quetta. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 111974m,
                            Title = "Townhouse in Quetta"
                        },
                        new
                        {
                            Id = 16,
                            Address = "118 Rawalpindi Road",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            City = "Rawalpindi",
                            Description = "Spacious modern villa located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 88615m,
                            Title = "Modern Villa in Rawalpindi"
                        },
                        new
                        {
                            Id = 17,
                            Address = "150 Faisalabad Road",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Faisalabad",
                            Description = "Spacious shop located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 15318434m,
                            Title = "Shop in Faisalabad"
                        },
                        new
                        {
                            Id = 18,
                            Address = "169 Sialkot Road",
                            Bathrooms = 1,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Sialkot",
                            Description = "Spacious modern villa located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 76442129m,
                            Title = "Modern Villa in Sialkot"
                        },
                        new
                        {
                            Id = 19,
                            Address = "6 Islamabad Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious penthouse located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 224485m,
                            Title = "Penthouse in Islamabad"
                        },
                        new
                        {
                            Id = 20,
                            Address = "59 Islamabad Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious shop located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 276848m,
                            Title = "Shop in Islamabad"
                        },
                        new
                        {
                            Id = 21,
                            Address = "89 Multan Road",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Multan",
                            Description = "Spacious townhouse located in Multan. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 55845m,
                            Title = "Townhouse in Multan"
                        },
                        new
                        {
                            Id = 22,
                            Address = "22 Rawalpindi Road",
                            Bathrooms = 4,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Rawalpindi",
                            Description = "Spacious commercial plot located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 196910m,
                            Title = "Commercial Plot in Rawalpindi"
                        },
                        new
                        {
                            Id = 23,
                            Address = "25 Karachi Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Karachi",
                            Description = "Spacious shop located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 66208476m,
                            Title = "Shop in Karachi"
                        },
                        new
                        {
                            Id = 24,
                            Address = "188 Gujranwala Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Gujranwala",
                            Description = "Spacious office space located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 72831m,
                            Title = "Office Space in Gujranwala"
                        },
                        new
                        {
                            Id = 25,
                            Address = "177 Sialkot Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Sialkot",
                            Description = "Spacious family home located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 128794m,
                            Title = "Family Home in Sialkot"
                        },
                        new
                        {
                            Id = 26,
                            Address = "84 Peshawar Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Peshawar",
                            Description = "Spacious family home located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 24423424m,
                            Title = "Family Home in Peshawar"
                        },
                        new
                        {
                            Id = 27,
                            Address = "193 Sialkot Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Sialkot",
                            Description = "Spacious townhouse located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 334377m,
                            Title = "Townhouse in Sialkot"
                        },
                        new
                        {
                            Id = 28,
                            Address = "161 Lahore Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Lahore",
                            Description = "Spacious family home located in Lahore. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 227482m,
                            Title = "Family Home in Lahore"
                        },
                        new
                        {
                            Id = 29,
                            Address = "40 Rawalpindi Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Rawalpindi",
                            Description = "Spacious townhouse located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 82143m,
                            Title = "Townhouse in Rawalpindi"
                        },
                        new
                        {
                            Id = 30,
                            Address = "54 Gujranwala Road",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            CarSpots = 0,
                            City = "Gujranwala",
                            Description = "Spacious modern villa located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 23227634m,
                            Title = "Modern Villa in Gujranwala"
                        },
                        new
                        {
                            Id = 31,
                            Address = "71 Sialkot Road",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 2,
                            City = "Sialkot",
                            Description = "Spacious studio flat located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 43572083m,
                            Title = "Studio Flat in Sialkot"
                        },
                        new
                        {
                            Id = 32,
                            Address = "191 Sialkot Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Sialkot",
                            Description = "Spacious luxury apartment located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 84735464m,
                            Title = "Luxury Apartment in Sialkot"
                        },
                        new
                        {
                            Id = 33,
                            Address = "4 Karachi Road",
                            Bathrooms = 4,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Karachi",
                            Description = "Spacious office space located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 31554236m,
                            Title = "Office Space in Karachi"
                        },
                        new
                        {
                            Id = 34,
                            Address = "196 Islamabad Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Islamabad",
                            Description = "Spacious modern villa located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 313416m,
                            Title = "Modern Villa in Islamabad"
                        },
                        new
                        {
                            Id = 35,
                            Address = "137 Islamabad Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious townhouse located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 25340m,
                            Title = "Townhouse in Islamabad"
                        },
                        new
                        {
                            Id = 36,
                            Address = "65 Multan Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Multan",
                            Description = "Spacious studio flat located in Multan. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 23573447m,
                            Title = "Studio Flat in Multan"
                        },
                        new
                        {
                            Id = 37,
                            Address = "1 Peshawar Road",
                            Bathrooms = 4,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Peshawar",
                            Description = "Spacious luxury apartment located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 76616474m,
                            Title = "Luxury Apartment in Peshawar"
                        },
                        new
                        {
                            Id = 38,
                            Address = "36 Multan Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Multan",
                            Description = "Spacious luxury apartment located in Multan. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 20569039m,
                            Title = "Luxury Apartment in Multan"
                        },
                        new
                        {
                            Id = 39,
                            Address = "84 Peshawar Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Peshawar",
                            Description = "Spacious penthouse located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 60460139m,
                            Title = "Penthouse in Peshawar"
                        },
                        new
                        {
                            Id = 40,
                            Address = "131 Faisalabad Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious townhouse located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 52122919m,
                            Title = "Townhouse in Faisalabad"
                        },
                        new
                        {
                            Id = 41,
                            Address = "64 Gujranwala Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Gujranwala",
                            Description = "Spacious family home located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 119307m,
                            Title = "Family Home in Gujranwala"
                        },
                        new
                        {
                            Id = 42,
                            Address = "83 Multan Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Multan",
                            Description = "Spacious commercial plot located in Multan. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 346585m,
                            Title = "Commercial Plot in Multan"
                        },
                        new
                        {
                            Id = 43,
                            Address = "62 Faisalabad Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious farmhouse located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 39535100m,
                            Title = "Farmhouse in Faisalabad"
                        },
                        new
                        {
                            Id = 44,
                            Address = "181 Faisalabad Road",
                            Bathrooms = 4,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious commercial plot located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 47002m,
                            Title = "Commercial Plot in Faisalabad"
                        },
                        new
                        {
                            Id = 45,
                            Address = "168 Gujranwala Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Gujranwala",
                            Description = "Spacious family home located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 332323m,
                            Title = "Family Home in Gujranwala"
                        },
                        new
                        {
                            Id = 46,
                            Address = "114 Multan Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Multan",
                            Description = "Spacious modern villa located in Multan. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 14269739m,
                            Title = "Modern Villa in Multan"
                        },
                        new
                        {
                            Id = 47,
                            Address = "5 Lahore Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 1,
                            City = "Lahore",
                            Description = "Spacious luxury apartment located in Lahore. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 36780450m,
                            Title = "Luxury Apartment in Lahore"
                        },
                        new
                        {
                            Id = 48,
                            Address = "158 Islamabad Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious office space located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 291636m,
                            Title = "Office Space in Islamabad"
                        },
                        new
                        {
                            Id = 49,
                            Address = "157 Islamabad Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Islamabad",
                            Description = "Spacious modern villa located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 15351m,
                            Title = "Modern Villa in Islamabad"
                        },
                        new
                        {
                            Id = 50,
                            Address = "171 Multan Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Multan",
                            Description = "Spacious shop located in Multan. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 241865m,
                            Title = "Shop in Multan"
                        },
                        new
                        {
                            Id = 51,
                            Address = "186 Quetta Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Quetta",
                            Description = "Spacious shop located in Quetta. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 286757m,
                            Title = "Shop in Quetta"
                        },
                        new
                        {
                            Id = 52,
                            Address = "181 Sialkot Road",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            CarSpots = 1,
                            City = "Sialkot",
                            Description = "Spacious townhouse located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 87136891m,
                            Title = "Townhouse in Sialkot"
                        },
                        new
                        {
                            Id = 53,
                            Address = "12 Lahore Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Lahore",
                            Description = "Spacious office space located in Lahore. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 35631687m,
                            Title = "Office Space in Lahore"
                        },
                        new
                        {
                            Id = 54,
                            Address = "176 Sialkot Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Sialkot",
                            Description = "Spacious office space located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 38112242m,
                            Title = "Office Space in Sialkot"
                        },
                        new
                        {
                            Id = 55,
                            Address = "40 Multan Road",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Multan",
                            Description = "Spacious modern villa located in Multan. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 200602m,
                            Title = "Modern Villa in Multan"
                        },
                        new
                        {
                            Id = 56,
                            Address = "142 Quetta Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 2,
                            City = "Quetta",
                            Description = "Spacious luxury apartment located in Quetta. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 44465738m,
                            Title = "Luxury Apartment in Quetta"
                        },
                        new
                        {
                            Id = 57,
                            Address = "175 Islamabad Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious commercial plot located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 222346m,
                            Title = "Commercial Plot in Islamabad"
                        },
                        new
                        {
                            Id = 58,
                            Address = "174 Gujranwala Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 2,
                            City = "Gujranwala",
                            Description = "Spacious shop located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 120586m,
                            Title = "Shop in Gujranwala"
                        },
                        new
                        {
                            Id = 59,
                            Address = "175 Karachi Road",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            CarSpots = 0,
                            City = "Karachi",
                            Description = "Spacious commercial plot located in Karachi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 295700m,
                            Title = "Commercial Plot in Karachi"
                        },
                        new
                        {
                            Id = 60,
                            Address = "57 Lahore Road",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 2,
                            City = "Lahore",
                            Description = "Spacious penthouse located in Lahore. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 169001m,
                            Title = "Penthouse in Lahore"
                        },
                        new
                        {
                            Id = 61,
                            Address = "94 Rawalpindi Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Rawalpindi",
                            Description = "Spacious luxury apartment located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 14297065m,
                            Title = "Luxury Apartment in Rawalpindi"
                        },
                        new
                        {
                            Id = 62,
                            Address = "68 Peshawar Road",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CarSpots = 2,
                            City = "Peshawar",
                            Description = "Spacious penthouse located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 70878741m,
                            Title = "Penthouse in Peshawar"
                        },
                        new
                        {
                            Id = 63,
                            Address = "77 Islamabad Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 2,
                            City = "Islamabad",
                            Description = "Spacious commercial plot located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 52062013m,
                            Title = "Commercial Plot in Islamabad"
                        },
                        new
                        {
                            Id = 64,
                            Address = "95 Quetta Road",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Quetta",
                            Description = "Spacious commercial plot located in Quetta. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 319926m,
                            Title = "Commercial Plot in Quetta"
                        },
                        new
                        {
                            Id = 65,
                            Address = "108 Islamabad Road",
                            Bathrooms = 3,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Islamabad",
                            Description = "Spacious shop located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 48125m,
                            Title = "Shop in Islamabad"
                        },
                        new
                        {
                            Id = 66,
                            Address = "66 Faisalabad Road",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious luxury apartment located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 225877m,
                            Title = "Luxury Apartment in Faisalabad"
                        },
                        new
                        {
                            Id = 67,
                            Address = "45 Peshawar Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Peshawar",
                            Description = "Spacious luxury apartment located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 46169248m,
                            Title = "Luxury Apartment in Peshawar"
                        },
                        new
                        {
                            Id = 68,
                            Address = "172 Islamabad Road",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious studio flat located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 313419m,
                            Title = "Studio Flat in Islamabad"
                        },
                        new
                        {
                            Id = 69,
                            Address = "113 Karachi Road",
                            Bathrooms = 4,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Karachi",
                            Description = "Spacious farmhouse located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 62080640m,
                            Title = "Farmhouse in Karachi"
                        },
                        new
                        {
                            Id = 70,
                            Address = "54 Gujranwala Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Gujranwala",
                            Description = "Spacious modern villa located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 56770m,
                            Title = "Modern Villa in Gujranwala"
                        },
                        new
                        {
                            Id = 71,
                            Address = "16 Karachi Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Karachi",
                            Description = "Spacious family home located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 18160452m,
                            Title = "Family Home in Karachi"
                        },
                        new
                        {
                            Id = 72,
                            Address = "8 Multan Road",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Multan",
                            Description = "Spacious office space located in Multan. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 205062m,
                            Title = "Office Space in Multan"
                        },
                        new
                        {
                            Id = 73,
                            Address = "160 Gujranwala Road",
                            Bathrooms = 4,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Gujranwala",
                            Description = "Spacious farmhouse located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 14217328m,
                            Title = "Farmhouse in Gujranwala"
                        },
                        new
                        {
                            Id = 74,
                            Address = "183 Islamabad Road",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Islamabad",
                            Description = "Spacious farmhouse located in Islamabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 74177m,
                            Title = "Farmhouse in Islamabad"
                        },
                        new
                        {
                            Id = 75,
                            Address = "83 Peshawar Road",
                            Bathrooms = 4,
                            Bedrooms = 2,
                            CarSpots = 0,
                            City = "Peshawar",
                            Description = "Spacious office space located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 80167166m,
                            Title = "Office Space in Peshawar"
                        },
                        new
                        {
                            Id = 76,
                            Address = "83 Quetta Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Quetta",
                            Description = "Spacious luxury apartment located in Quetta. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 17146710m,
                            Title = "Luxury Apartment in Quetta"
                        },
                        new
                        {
                            Id = 77,
                            Address = "45 Rawalpindi Road",
                            Bathrooms = 1,
                            Bedrooms = 5,
                            CarSpots = 1,
                            City = "Rawalpindi",
                            Description = "Spacious luxury apartment located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 64329690m,
                            Title = "Luxury Apartment in Rawalpindi"
                        },
                        new
                        {
                            Id = 78,
                            Address = "92 Peshawar Road",
                            Bathrooms = 2,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Peshawar",
                            Description = "Spacious shop located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 8196958m,
                            Title = "Shop in Peshawar"
                        },
                        new
                        {
                            Id = 79,
                            Address = "13 Faisalabad Road",
                            Bathrooms = 3,
                            Bedrooms = 5,
                            CarSpots = 2,
                            City = "Faisalabad",
                            Description = "Spacious shop located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 102328m,
                            Title = "Shop in Faisalabad"
                        },
                        new
                        {
                            Id = 80,
                            Address = "151 Karachi Road",
                            Bathrooms = 2,
                            Bedrooms = 5,
                            CarSpots = 2,
                            City = "Karachi",
                            Description = "Spacious studio flat located in Karachi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 40136868m,
                            Title = "Studio Flat in Karachi"
                        },
                        new
                        {
                            Id = 81,
                            Address = "118 Faisalabad Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 0,
                            City = "Faisalabad",
                            Description = "Spacious office space located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 5548360m,
                            Title = "Office Space in Faisalabad"
                        },
                        new
                        {
                            Id = 82,
                            Address = "95 Quetta Road",
                            Bathrooms = 1,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Quetta",
                            Description = "Spacious luxury apartment located in Quetta. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 264154m,
                            Title = "Luxury Apartment in Quetta"
                        },
                        new
                        {
                            Id = 83,
                            Address = "148 Faisalabad Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 2,
                            City = "Faisalabad",
                            Description = "Spacious penthouse located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 17756m,
                            Title = "Penthouse in Faisalabad"
                        },
                        new
                        {
                            Id = 84,
                            Address = "75 Lahore Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 1,
                            City = "Lahore",
                            Description = "Spacious penthouse located in Lahore. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 50752876m,
                            Title = "Penthouse in Lahore"
                        },
                        new
                        {
                            Id = 85,
                            Address = "190 Peshawar Road",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 1,
                            City = "Peshawar",
                            Description = "Spacious penthouse located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 79785679m,
                            Title = "Penthouse in Peshawar"
                        },
                        new
                        {
                            Id = 86,
                            Address = "180 Quetta Road",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Quetta",
                            Description = "Spacious farmhouse located in Quetta. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 12470603m,
                            Title = "Farmhouse in Quetta"
                        },
                        new
                        {
                            Id = 87,
                            Address = "92 Sialkot Road",
                            Bathrooms = 4,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Sialkot",
                            Description = "Spacious shop located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 346535m,
                            Title = "Shop in Sialkot"
                        },
                        new
                        {
                            Id = 88,
                            Address = "155 Faisalabad Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Faisalabad",
                            Description = "Spacious office space located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 69278981m,
                            Title = "Office Space in Faisalabad"
                        },
                        new
                        {
                            Id = 89,
                            Address = "86 Karachi Road",
                            Bathrooms = 2,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Karachi",
                            Description = "Spacious luxury apartment located in Karachi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 280289m,
                            Title = "Luxury Apartment in Karachi"
                        },
                        new
                        {
                            Id = 90,
                            Address = "20 Lahore Road",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Lahore",
                            Description = "Spacious family home located in Lahore. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 61116m,
                            Title = "Family Home in Lahore"
                        },
                        new
                        {
                            Id = 91,
                            Address = "161 Karachi Road",
                            Bathrooms = 3,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Karachi",
                            Description = "Spacious townhouse located in Karachi. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 257026m,
                            Title = "Townhouse in Karachi"
                        },
                        new
                        {
                            Id = 92,
                            Address = "19 Gujranwala Road",
                            Bathrooms = 4,
                            Bedrooms = 2,
                            CarSpots = 0,
                            City = "Gujranwala",
                            Description = "Spacious commercial plot located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 35567788m,
                            Title = "Commercial Plot in Gujranwala"
                        },
                        new
                        {
                            Id = 93,
                            Address = "63 Faisalabad Road",
                            Bathrooms = 2,
                            Bedrooms = 6,
                            CarSpots = 1,
                            City = "Faisalabad",
                            Description = "Spacious modern villa located in Faisalabad. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 218576m,
                            Title = "Modern Villa in Faisalabad"
                        },
                        new
                        {
                            Id = 94,
                            Address = "154 Sialkot Road",
                            Bathrooms = 1,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Sialkot",
                            Description = "Spacious office space located in Sialkot. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 336611m,
                            Title = "Office Space in Sialkot"
                        },
                        new
                        {
                            Id = 95,
                            Address = "102 Quetta Road",
                            Bathrooms = 1,
                            Bedrooms = 6,
                            CarSpots = 2,
                            City = "Quetta",
                            Description = "Spacious townhouse located in Quetta. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 83231m,
                            Title = "Townhouse in Quetta"
                        },
                        new
                        {
                            Id = 96,
                            Address = "55 Lahore Road",
                            Bathrooms = 3,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Lahore",
                            Description = "Spacious office space located in Lahore. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 36051023m,
                            Title = "Office Space in Lahore"
                        },
                        new
                        {
                            Id = 97,
                            Address = "140 Peshawar Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Peshawar",
                            Description = "Spacious townhouse located in Peshawar. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 61487065m,
                            Title = "Townhouse in Peshawar"
                        },
                        new
                        {
                            Id = 98,
                            Address = "164 Rawalpindi Road",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            CarSpots = 0,
                            City = "Rawalpindi",
                            Description = "Spacious office space located in Rawalpindi. Ideal for families and professionals.",
                            ListingType = "Sale",
                            Price = 45126362m,
                            Title = "Office Space in Rawalpindi"
                        },
                        new
                        {
                            Id = 99,
                            Address = "37 Lahore Road",
                            Bathrooms = 4,
                            Bedrooms = 1,
                            CarSpots = 0,
                            City = "Lahore",
                            Description = "Spacious farmhouse located in Lahore. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 184724m,
                            Title = "Farmhouse in Lahore"
                        },
                        new
                        {
                            Id = 100,
                            Address = "39 Gujranwala Road",
                            Bathrooms = 4,
                            Bedrooms = 3,
                            CarSpots = 0,
                            City = "Gujranwala",
                            Description = "Spacious commercial plot located in Gujranwala. Ideal for families and professionals.",
                            ListingType = "Rent",
                            Price = 239596m,
                            Title = "Commercial Plot in Gujranwala"
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.PropertyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("PropertyImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PropertyId = 1,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,LuxuryApartment"
                        },
                        new
                        {
                            Id = 2,
                            PropertyId = 2,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,FamilyHome"
                        },
                        new
                        {
                            Id = 3,
                            PropertyId = 3,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,OfficeSpace"
                        },
                        new
                        {
                            Id = 4,
                            PropertyId = 4,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,ModernVilla"
                        },
                        new
                        {
                            Id = 5,
                            PropertyId = 5,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,StudioFlat"
                        },
                        new
                        {
                            Id = 6,
                            PropertyId = 6,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,LuxuryApartment"
                        },
                        new
                        {
                            Id = 7,
                            PropertyId = 7,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,FamilyHome"
                        },
                        new
                        {
                            Id = 8,
                            PropertyId = 8,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,Townhouse"
                        },
                        new
                        {
                            Id = 9,
                            PropertyId = 9,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,ModernVilla"
                        },
                        new
                        {
                            Id = 10,
                            PropertyId = 10,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,OfficeSpace"
                        },
                        new
                        {
                            Id = 11,
                            PropertyId = 11,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,CommercialPlot"
                        },
                        new
                        {
                            Id = 12,
                            PropertyId = 12,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Farmhouse"
                        },
                        new
                        {
                            Id = 13,
                            PropertyId = 13,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,Shop"
                        },
                        new
                        {
                            Id = 14,
                            PropertyId = 14,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,LuxuryApartment"
                        },
                        new
                        {
                            Id = 15,
                            PropertyId = 15,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,Townhouse"
                        },
                        new
                        {
                            Id = 16,
                            PropertyId = 16,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,ModernVilla"
                        },
                        new
                        {
                            Id = 17,
                            PropertyId = 17,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Shop"
                        },
                        new
                        {
                            Id = 18,
                            PropertyId = 18,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,ModernVilla"
                        },
                        new
                        {
                            Id = 19,
                            PropertyId = 19,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,Penthouse"
                        },
                        new
                        {
                            Id = 20,
                            PropertyId = 20,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,Shop"
                        },
                        new
                        {
                            Id = 21,
                            PropertyId = 21,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,Townhouse"
                        },
                        new
                        {
                            Id = 22,
                            PropertyId = 22,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,CommercialPlot"
                        },
                        new
                        {
                            Id = 23,
                            PropertyId = 23,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,Shop"
                        },
                        new
                        {
                            Id = 24,
                            PropertyId = 24,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,OfficeSpace"
                        },
                        new
                        {
                            Id = 25,
                            PropertyId = 25,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,FamilyHome"
                        },
                        new
                        {
                            Id = 26,
                            PropertyId = 26,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,FamilyHome"
                        },
                        new
                        {
                            Id = 27,
                            PropertyId = 27,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,Townhouse"
                        },
                        new
                        {
                            Id = 28,
                            PropertyId = 28,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,FamilyHome"
                        },
                        new
                        {
                            Id = 29,
                            PropertyId = 29,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,Townhouse"
                        },
                        new
                        {
                            Id = 30,
                            PropertyId = 30,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,ModernVilla"
                        },
                        new
                        {
                            Id = 31,
                            PropertyId = 31,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,StudioFlat"
                        },
                        new
                        {
                            Id = 32,
                            PropertyId = 32,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,LuxuryApartment"
                        },
                        new
                        {
                            Id = 33,
                            PropertyId = 33,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,OfficeSpace"
                        },
                        new
                        {
                            Id = 34,
                            PropertyId = 34,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,ModernVilla"
                        },
                        new
                        {
                            Id = 35,
                            PropertyId = 35,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,Townhouse"
                        },
                        new
                        {
                            Id = 36,
                            PropertyId = 36,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,StudioFlat"
                        },
                        new
                        {
                            Id = 37,
                            PropertyId = 37,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,LuxuryApartment"
                        },
                        new
                        {
                            Id = 38,
                            PropertyId = 38,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,LuxuryApartment"
                        },
                        new
                        {
                            Id = 39,
                            PropertyId = 39,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,Penthouse"
                        },
                        new
                        {
                            Id = 40,
                            PropertyId = 40,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Townhouse"
                        },
                        new
                        {
                            Id = 41,
                            PropertyId = 41,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,FamilyHome"
                        },
                        new
                        {
                            Id = 42,
                            PropertyId = 42,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,CommercialPlot"
                        },
                        new
                        {
                            Id = 43,
                            PropertyId = 43,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Farmhouse"
                        },
                        new
                        {
                            Id = 44,
                            PropertyId = 44,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,CommercialPlot"
                        },
                        new
                        {
                            Id = 45,
                            PropertyId = 45,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,FamilyHome"
                        },
                        new
                        {
                            Id = 46,
                            PropertyId = 46,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,ModernVilla"
                        },
                        new
                        {
                            Id = 47,
                            PropertyId = 47,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,LuxuryApartment"
                        },
                        new
                        {
                            Id = 48,
                            PropertyId = 48,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,OfficeSpace"
                        },
                        new
                        {
                            Id = 49,
                            PropertyId = 49,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,ModernVilla"
                        },
                        new
                        {
                            Id = 50,
                            PropertyId = 50,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,Shop"
                        },
                        new
                        {
                            Id = 51,
                            PropertyId = 51,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,Shop"
                        },
                        new
                        {
                            Id = 52,
                            PropertyId = 52,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,Townhouse"
                        },
                        new
                        {
                            Id = 53,
                            PropertyId = 53,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,OfficeSpace"
                        },
                        new
                        {
                            Id = 54,
                            PropertyId = 54,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,OfficeSpace"
                        },
                        new
                        {
                            Id = 55,
                            PropertyId = 55,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,ModernVilla"
                        },
                        new
                        {
                            Id = 56,
                            PropertyId = 56,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,LuxuryApartment"
                        },
                        new
                        {
                            Id = 57,
                            PropertyId = 57,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,CommercialPlot"
                        },
                        new
                        {
                            Id = 58,
                            PropertyId = 58,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,Shop"
                        },
                        new
                        {
                            Id = 59,
                            PropertyId = 59,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,CommercialPlot"
                        },
                        new
                        {
                            Id = 60,
                            PropertyId = 60,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,Penthouse"
                        },
                        new
                        {
                            Id = 61,
                            PropertyId = 61,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,LuxuryApartment"
                        },
                        new
                        {
                            Id = 62,
                            PropertyId = 62,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,Penthouse"
                        },
                        new
                        {
                            Id = 63,
                            PropertyId = 63,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,CommercialPlot"
                        },
                        new
                        {
                            Id = 64,
                            PropertyId = 64,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,CommercialPlot"
                        },
                        new
                        {
                            Id = 65,
                            PropertyId = 65,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,Shop"
                        },
                        new
                        {
                            Id = 66,
                            PropertyId = 66,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,LuxuryApartment"
                        },
                        new
                        {
                            Id = 67,
                            PropertyId = 67,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,LuxuryApartment"
                        },
                        new
                        {
                            Id = 68,
                            PropertyId = 68,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,StudioFlat"
                        },
                        new
                        {
                            Id = 69,
                            PropertyId = 69,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,Farmhouse"
                        },
                        new
                        {
                            Id = 70,
                            PropertyId = 70,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,ModernVilla"
                        },
                        new
                        {
                            Id = 71,
                            PropertyId = 71,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,FamilyHome"
                        },
                        new
                        {
                            Id = 72,
                            PropertyId = 72,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Multan,OfficeSpace"
                        },
                        new
                        {
                            Id = 73,
                            PropertyId = 73,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,Farmhouse"
                        },
                        new
                        {
                            Id = 74,
                            PropertyId = 74,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Islamabad,Farmhouse"
                        },
                        new
                        {
                            Id = 75,
                            PropertyId = 75,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,OfficeSpace"
                        },
                        new
                        {
                            Id = 76,
                            PropertyId = 76,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,LuxuryApartment"
                        },
                        new
                        {
                            Id = 77,
                            PropertyId = 77,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,LuxuryApartment"
                        },
                        new
                        {
                            Id = 78,
                            PropertyId = 78,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,Shop"
                        },
                        new
                        {
                            Id = 79,
                            PropertyId = 79,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Shop"
                        },
                        new
                        {
                            Id = 80,
                            PropertyId = 80,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,StudioFlat"
                        },
                        new
                        {
                            Id = 81,
                            PropertyId = 81,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,OfficeSpace"
                        },
                        new
                        {
                            Id = 82,
                            PropertyId = 82,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,LuxuryApartment"
                        },
                        new
                        {
                            Id = 83,
                            PropertyId = 83,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,Penthouse"
                        },
                        new
                        {
                            Id = 84,
                            PropertyId = 84,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,Penthouse"
                        },
                        new
                        {
                            Id = 85,
                            PropertyId = 85,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,Penthouse"
                        },
                        new
                        {
                            Id = 86,
                            PropertyId = 86,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,Farmhouse"
                        },
                        new
                        {
                            Id = 87,
                            PropertyId = 87,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,Shop"
                        },
                        new
                        {
                            Id = 88,
                            PropertyId = 88,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,OfficeSpace"
                        },
                        new
                        {
                            Id = 89,
                            PropertyId = 89,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,LuxuryApartment"
                        },
                        new
                        {
                            Id = 90,
                            PropertyId = 90,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,FamilyHome"
                        },
                        new
                        {
                            Id = 91,
                            PropertyId = 91,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Karachi,Townhouse"
                        },
                        new
                        {
                            Id = 92,
                            PropertyId = 92,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,CommercialPlot"
                        },
                        new
                        {
                            Id = 93,
                            PropertyId = 93,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Faisalabad,ModernVilla"
                        },
                        new
                        {
                            Id = 94,
                            PropertyId = 94,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Sialkot,OfficeSpace"
                        },
                        new
                        {
                            Id = 95,
                            PropertyId = 95,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Quetta,Townhouse"
                        },
                        new
                        {
                            Id = 96,
                            PropertyId = 96,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,OfficeSpace"
                        },
                        new
                        {
                            Id = 97,
                            PropertyId = 97,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Peshawar,Townhouse"
                        },
                        new
                        {
                            Id = 98,
                            PropertyId = 98,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Rawalpindi,OfficeSpace"
                        },
                        new
                        {
                            Id = 99,
                            PropertyId = 99,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Lahore,Farmhouse"
                        },
                        new
                        {
                            Id = 100,
                            PropertyId = 100,
                            Url = "https://source.unsplash.com/600x400/?house,pakistan,Gujranwala,CommercialPlot"
                        });
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.Favorite", b =>
                {
                    b.HasOne("RealEstatePortal.Domain.Models.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.PropertyImage", b =>
                {
                    b.HasOne("RealEstatePortal.Domain.Models.Property", "Property")
                        .WithMany("Images")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.Property", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("RealEstatePortal.Domain.Models.User", b =>
                {
                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
